### ISSUE TITLE
Zijn dit buttons?

### ISSUE THREAD

**Issue by r20222** [SamaraFellaDina/the-client-website#7]
https://github.com/SamaraFellaDina/the-client-website/blob/454d6f849630d54fc8a087b0c7e09f32be010e4c/index.html#L27-L30

Sections is meer voor het structureren van gedeeltes op de webpagina.

**Comment by Treppord** [comment]
Wij zijn nog in twijfel of wij dit buttons willen maken, omdat de functionaliteit van de lijst knoppen later op onze planning staat. Maar mega bedankt voor het definieren van <section> <3
